name: Update Global Population Watch

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  run-tracker:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python scraper.py

    - name: Commit updates
      run: |
        git config --global user.name "tracker"
        git config --global user.email "tracker@github.com"
        git add data/
        git commit -m "update dataset tracker" || echo "no changes"
        git push
